version: '3.8'

services:
  db:
    image: postgres
    container_name: db-styleconfigurator
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: styleconfigurator
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-styleconfigurator-data:/var/lib/postgresql/data

volumes:
  db-styleconfigurator-data:
    driver: local