version: '3.8'

services:
  style-configurator:
    container_name: styleConfigurator
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVER_PORT: 8082
      DB_URL: "db:5432/styleconfigurator"
      DB_USERNAME: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - db
    networks:
      - db_network
      - FLOMEE-services

  db:
    image: postgres
    container_name: db-styleconfigurator
    environment:
      POSTGRES_DB: styleconfigurator
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db-styleconfigurator-data:/var/lib/postgresql/data
    networks:
      - db_network


networks:
  db_network:
    driver: bridge
    name: db_network
  FLOMEE-services:
    driver: bridge
    external: true

volumes:
  db-styleconfigurator-data:
    driver: local