server:
  port: 8082
spring:
  application:
    name: StyleConfigurator
  datasource:
    url: jdbc:postgresql://${db.url}
    username: ${db.username}
    password: ${db.password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

db:
  url: localhost:5432/styleconfigurator
  username: ${POSTGRES_USER}
  password: ${POSTGRES_PASSWORD}
